Use odl errorprone feature
Instead of adding bundle into the feature.xml file, use the
existing feature from opendaylight called odl-errorprone.

Removing the errorprone bundle from feature.xml causes
ClassNotFoundException: com.google.protobuf.Message.
Because of this, we need to add the missing bundles as well.

JIRA: GNMI-27
Change-Id: I251ba41f6cbbe98ecf6c5f1bff405900ad7ff5fb
Signed-off-by: tobias.pobocik <tobias.pobocik@pantheon.tech>
(cherry picked from commit 4731bc76fb0b4451a0af9d2960d6cb7dadf6de17)